/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package four_in_a_row.gui;

import four_in_a_row.Game;
import four_in_a_row.players.Player;
import four_in_a_row.players.PlayerAI;
import four_in_a_row.players.PlayerGUI;
import four_in_a_row.players.PlayerRandom;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Armin Mokri
 */
public class JFrameMain extends javax.swing.JFrame {

    //
    private JPanel jPanelPlayer2Action;
    private JPanel jPanelgame;
    //
    //private JLabel[] jLabelsAction;
    private JLabel[][] jLabelsGame;
    private int nutSize = 30;
    //

    //private Board board;
    private Game game;

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        setLocationCenter();
    }

    private void setLocationCenter() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox_BoardSize = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPlayer1Level = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPlayer1Type = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPlayer2Type = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxPlayer2Level = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxDebug = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Four In The Row");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jButton1.setText("New Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox_BoardSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jComboBox_BoardSize.setSelectedIndex(2);

        jLabel1.setText("Board Size:");

        jLabel2.setText("Game Level:");

        jComboBoxPlayer1Level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxPlayer1Level.setSelectedIndex(2);

        jLabel3.setForeground(java.awt.Color.blue);
        jLabel3.setText("Player 1:");

        jComboBoxPlayer1Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System(Artificial Intelligence)", "System(Random)" }));
        jComboBoxPlayer1Type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPlayer1TypeItemStateChanged(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("Player 2:");

        jComboBoxPlayer2Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System(Artificial Intelligence)", "System(Random)", "User" }));
        jComboBoxPlayer2Type.setSelectedIndex(2);
        jComboBoxPlayer2Type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPlayer2TypeItemStateChanged(evt);
            }
        });

        jLabel5.setText("Game Level:");

        jComboBoxPlayer2Level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxPlayer2Level.setSelectedIndex(2);
        jComboBoxPlayer2Level.setEnabled(false);

        jLabel6.setText("Move Limit Time:");

        jSlider1.setValue(10);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel7.setText("10 seconds");

        jLabel8.setText("Debug Mode:");

        jComboBoxDebug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPlayer1Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPlayer1Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPlayer2Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPlayer2Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDebug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_BoardSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_BoardSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxDebug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxPlayer1Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxPlayer1Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxPlayer2Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxPlayer2Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "new_game");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, "game");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        // board size
        int board_size = Integer.parseInt(jComboBox_BoardSize.getSelectedItem().toString());
        int time_limit = jSlider1.getValue();
        boolean debug = jComboBoxDebug.getSelectedItem().toString() == "Yes";

        // Player 1 configs
        Player player1 = null;
        String player1_type = jComboBoxPlayer1Type.getSelectedItem().toString();
        int player1_game_level = Integer.parseInt(jComboBoxPlayer1Level.getSelectedItem().toString());
        // System(Artificial Intelligence), System(Random)
        if (player1_type.equals("System(Artificial Intelligence)")) {
            player1 = new PlayerAI(1, player1_game_level, debug);
        } else if (player1_type.equals("System(Random)")) {
            player1 = new PlayerRandom(1);
        }

        // Player 2 configs
        Player player2 = null;
        String player2_type = jComboBoxPlayer2Type.getSelectedItem().toString();
        int player2_game_level = Integer.parseInt(jComboBoxPlayer2Level.getSelectedItem().toString());
        // System(Artificial Intelligence), System(Random), User
        if (player2_type.equals("System(Artificial Intelligence)")) {
            player2 = new PlayerAI(2, player2_game_level, debug);
        } else if (player2_type.equals("System(Random)")) {
            player2 = new PlayerRandom(2);
        } else if (player2_type.equals("User")) {
            PlayerGUI playerGUI = new PlayerGUI(2, board_size, nutSize);
            player2 = playerGUI;
            // jPanelAction
            jPanelPlayer2Action = new JPanel();
            jPanelPlayer2Action.setBackground(Color.WHITE);
            jPanelPlayer2Action.setLayout(new GridLayout(1, board_size));
            jPanelPlayer2Action.setSize(board_size * nutSize, nutSize);
            for (int i = 0; i < board_size; i++) {
                jPanelPlayer2Action.add(playerGUI.getjLabelsAction()[i]);
            }
            jPanel2.add(jPanelPlayer2Action, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, board_size * nutSize, nutSize));
        }

        //
        game = new Game(player1, player2, board_size, time_limit, this, debug);

        // jPanelgame
        jPanelgame = new JPanel();
        jPanelgame.setBackground(Color.BLACK);
        jPanelgame.setLayout(new GridLayout(game.getBoard().size, game.getBoard().size));
        jPanelgame.setSize(nutSize * game.getBoard().size, nutSize * game.getBoard().size);
        jLabelsGame = new JLabel[game.getBoard().size][game.getBoard().size];
        for (int i = 0; i < game.getBoard().size; i++) {
            for (int j = 0; j < game.getBoard().size; j++) {
                jLabelsGame[i][j] = new JLabel();
                jLabelsGame[i][j].setSize(nutSize, nutSize);
                jPanelgame.add(jLabelsGame[i][j]);

            }
        }
        jPanel2.add(jPanelgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, nutSize, nutSize * game.getBoard().size, nutSize * game.getBoard().size));

        // set frame size and location
        this.setSize(this.getInsets().left + this.getInsets().right + (nutSize * game.getBoard().size),
                this.getInsets().top + this.getInsets().bottom + (nutSize * (game.getBoard().size + 1)));
        this.setLocationCenter();

        //
        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(jPanel2.getParent(), "game");

        //
        printGame();

        game.start();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxPlayer1TypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPlayer1TypeItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxPlayer1Type.getSelectedItem().toString().equals("System(Artificial Intelligence)")) {
            jComboBoxPlayer1Level.setEnabled(true);
        } else {
            jComboBoxPlayer1Level.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxPlayer1TypeItemStateChanged

    private void jComboBoxPlayer2TypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPlayer2TypeItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxPlayer2Type.getSelectedItem().toString().equals("System(Artificial Intelligence)")) {
            jComboBoxPlayer2Level.setEnabled(true);
        } else {
            jComboBoxPlayer2Level.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxPlayer2TypeItemStateChanged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        jLabel7.setText(jSlider1.getValue() + " seconds");
    }//GEN-LAST:event_jSlider1StateChanged

    public void printGame() {
        for (int i = 0; i < game.getBoard().size; i++) {
            for (int j = 0; j < game.getBoard().size; j++) {
                switch (game.getBoard().getCell(i, j).getColor()) {
                    case 0:
                        jLabelsGame[game.getBoard().size - 1 - i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white25.png")));
                        break;
                    case 1:
                        jLabelsGame[game.getBoard().size - 1 - i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue25.png")));
                        break;
                    case 2:
                        jLabelsGame[game.getBoard().size - 1 - i][j].setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red25.png")));
                        break;
                    default:
                        break;
                }
            }
        }
        this.repaint();
    }
    
    public void showResult(String string){
        JOptionPane.showMessageDialog(null, string);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxDebug;
    private javax.swing.JComboBox<String> jComboBoxPlayer1Level;
    private javax.swing.JComboBox<String> jComboBoxPlayer1Type;
    private javax.swing.JComboBox<String> jComboBoxPlayer2Level;
    private javax.swing.JComboBox<String> jComboBoxPlayer2Type;
    private javax.swing.JComboBox<String> jComboBox_BoardSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
